FROM alpine:3.19

RUN apk add --no-cache \
    git \
    wget \
    autoconf \
    cmake \
    dpkg-dev \
    dpkg \
    file \
    g++ \
    gcc \
    libc-dev \
    make \
    pkgconf \
    re2c \
    tar \
    xz \
    bison \
    pcre-dev \
    libxml2-dev \
    sqlite-dev \
    libpng-dev \
    freetype-dev \
    oniguruma-dev \
    libapparmor-dev \
    bzip2-dev \
    curl-dev \
    enchant2-dev \
    libavif-dev \
    libwebp-dev \
    jpeg-dev \
    libxpm-dev \
    gmp-dev \
    icu-dev \
    openldap-dev \
    unixodbc-dev \
    freetds-dev \
    libpq-dev \
    net-snmp-dev \
    argon2-dev \
    tidyhtml-dev \
    libxslt-dev \
    libzip-dev \
    aspell-dev \
    capstone-dev \
    libselinux-dev \
    apache2-dev \
    apache2 \
    vim \
    && mkdir -p /opt

COPY cmake /opt/cmake
